/**
 * Build-time API bundler: compiles server/api-src/handler.ts (+ server/app.ts
 * and all imports) into a single self-contained CommonJS bundle at
 * api/dist.cjs, then emits the Vercel catch-all runtime entry api/[...path].js
 * (plain CJS shim). Keeping the TS source OUT of api/ avoids Vercel's
 * "conflicting paths" rule while [...path].js keeps the /api/* catch-all.
 * Vercel's build command runs this after `vite build` (see package.json).
 */
import { build } from 'esbuild';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';

await build({
  entryPoints: ['server/api-src/handler.ts'],
  outfile: 'api/dist.cjs',
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  minify: false,
  sourcemap: false,
  logLevel: 'info',
});

// Runtime catch-all: Vercel maps api/[...path].js to every /api/* request.
writeFileSync(
  'api/[...path].js',
  [
    '// AUTO-GENERATED by scripts/build-api.mjs — do not edit.',
    'const handler = require("./dist.cjs");',
    'module.exports = handler.default || handler;',
    '',
  ].join('\n')
);

// Force CommonJS resolution inside api/ (repo root is "type": "module").
mkdirSync('api', { recursive: true });
writeFileSync('api/package.json', JSON.stringify({ type: 'commonjs' }, null, 2));

// Clear stale artifacts from earlier attempts.
if (existsSync('api/index.ts')) rmSync('api/index.ts');
if (existsSync('api/index.js')) rmSync('api/index.js');
if (existsSync('api/handler.ts')) rmSync('api/handler.ts');

console.log('API bundle ready: api/dist.cjs + api/[...path].js');
