/**
 * Build-time API bundler: compiles api/[...path].ts (+ server/app.ts and all
 * imports) into a single self-contained CommonJS file at api/dist.cjs.
 * Vercel's build command runs this BEFORE its own compilation so the runtime
 * entry can load plain CJS (avoids the extensionless-ESM runtime failure).
 */
import { build } from 'esbuild';
import { cpSync, existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';

// Bundle the API into one CJS file (deps included — Vercel installs devDeps
// during build, so esbuild is available here).
await build({
  entryPoints: ['api/handler.ts'],
  outfile: 'api/dist.cjs',
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node20',
  minify: false,
  sourcemap: false,
  logLevel: 'info',
});

// Emit the runtime entry Vercel executes: a tiny CJS shim that requires the
// self-contained bundle (api/package.json pins type=commonjs for this dir).
writeFileSync(
  'api/index.js',
  [
    '// AUTO-GENERATED by scripts/build-api.mjs — do not edit.',
    'const handler = require("./dist.cjs");',
    'module.exports = handler.default || handler;',
    '',
  ].join('\n')
);

// Force CJS resolution for the api directory regardless of root "type": "module".
mkdirSync('api', { recursive: true });
writeFileSync('api/package.json', JSON.stringify({ type: 'commonjs' }, null, 2));

// Remove stale artifacts from earlier attempts so Vercel never sees
// conflicting function paths.
if (existsSync('api/index.ts')) rmSync('api/index.ts');

console.log('API bundle ready: api/dist.cjs + api/index.js');
